const wheelConfig = {
    wheelOptions: [
        "Apple15",
        "Orange15",
        "Melon15",
        "Grapse15",
        "Iphone10",
        "TV10",
        "Nothing15",
        "MainPrize5",
    ],
    wheelProbablility: [
        "Apple15",
        "Apple15",
        "Apple15",
        "Orange15",
        "Orange15",
        "Orange15",
        "Melon15",
        "Melon15",
        "Melon15",
        "Grapse15",
        "Grapse15",
        "Grapse15",
        "Iphone10",
        "Iphone10",
        "TV10",
        "TV10",
        "Nothing15",
        "Nothing15",
        "Nothing15",
        "MainPrize5",
    ],
    wheelColours: [
        "#db7093",
        "#20b2aa",
        "#d63e92",
        "#daa520",
        "#ff340f",
        "#ff7f50",
        "#3cb371",
        "#4169e1",
    ],
}
export default wheelConfig
